import type { DramaKnowledge } from '@drama-buddy/shared/knowledge';

export const bettercallsaul: DramaKnowledge = {
  id: 'bettercallsaul',
  title: 'Better Call Saul',
  aliases: ['风骚律师', 'BCS', 'Saul Goodman'],
  totalEpisodes: 63,
  genre: ['犯罪', '剧情', '法律'],
  year: 2015,
  synopsis: 'Breaking Bad 前传。讲述落魄律师 Jimmy McGill 如何一步步蜕变为黑心律师 Saul Goodman 的故事，同时揭示 Mike Ehrmantraut 的过往。',
  characters: [
    {
      name: 'Jimmy McGill',
      aliases: ['Saul Goodman', 'Slippin Jimmy', 'Gene Takavic', 'Viktor'],
      actor: 'Bob Odenkirk',
      description: '从小骗子到合法律师再到犯罪律师的转变。每一次试图做好人都被命运和自身性格拉回歧途。',
      personality: '口才极佳、善于变通、渴望认可、自毁倾向、有同理心但选择性忽略',
      firstAppearance: 1,
    },
    {
      name: 'Kim Wexler',
      aliases: ['Kim', '金'],
      actor: 'Rhea Seehorn',
      description: 'Jimmy 的灵魂伴侣和事业伙伴。从正义律师逐渐被 Jimmy 的世界吸引，展现出比 Jimmy 更危险的一面。',
      personality: '自律、果断、有正义感但享受犯规的刺激、极度压抑',
      firstAppearance: 1,
    },
    {
      name: 'Mike Ehrmantraut',
      aliases: ['Mike', '老麦'],
      actor: 'Jonathan Banks',
      description: '前费城警察，因儿子之死堕入犯罪世界。为 Gus Fring 担任安保顾问和清洁工。',
      personality: '沉默寡言、极度职业化、重视家人、对暴力冷漠但有底线',
      firstAppearance: 1,
    },
    {
      name: 'Chuck McGill',
      aliases: ['Chuck', '查克'],
      actor: 'Michael McKean',
      description: 'Jimmy 的哥哥，HHM 律师事务所合伙人。患有"电磁过敏症"，是 Jimmy 成长道路上最大的阻碍和动力。',
      personality: '才华横溢、嫉妒心强、自以为正义、控制欲强',
      firstAppearance: 1,
    },
    {
      name: 'Gus Fring',
      aliases: ['炸鸡叔', 'The Chicken Man', 'Gustavo'],
      actor: 'Giancarlo Esposito',
      description: '洛斯波尔斯炸鸡连锁老板，暗中经营庞大毒品帝国。极度冷静理性的反派。',
      personality: '伪善、极度自律、隐忍、复仇驱动、完美主义',
      firstAppearance: 15, // S2E11
    },
    {
      name: 'Nacho Varga',
      aliases: ['Nacho', '纳乔'],
      actor: 'Michael Mando',
      description: '萨拉曼卡贩毒集团成员，试图摆脱犯罪生活保护家人。夹在 Gus 和萨拉曼卡之间。',
      personality: '聪明、忠于家人、被迫犯罪、有良知',
      firstAppearance: 1,
    },
    {
      name: 'Lalo Salamanca',
      aliases: ['Lalo', '拉罗'],
      actor: 'Tony Dalton',
      description: '萨拉曼卡家族最危险的成员。极具魅力但残忍无情，是 Gus Fring 最大的威胁。',
      personality: '迷人、暴力、聪明、不可预测、享乐主义',
      firstAppearance: 32, // S4E08
    },
    {
      name: 'Howard Hamlin',
      aliases: ['Howard', '霍华德'],
      actor: 'Patrick Fabian',
      description: 'HHM 律师事务所合伙人，表面光鲜亮丽。逐渐成为 Jimmy 和 Kim 阴谋的受害者。',
      personality: '体面、虚荣、善意但居高临下、脆弱',
      firstAppearance: 1,
    },
  ],
  relationships: [
    { from: 'Jimmy McGill', to: 'Kim Wexler', type: 'couple', description: '灵魂伴侣，互相成就也互相毁灭' },
    { from: 'Jimmy McGill', to: 'Chuck McGill', type: 'family', description: '兄弟间的爱恨纠葛，Chuck的否定是Jimmy堕落的催化剂' },
    { from: 'Jimmy McGill', to: 'Howard Hamlin', type: 'rival', description: '从嫉恨到彻底摧毁', revealedAt: 40 },
    { from: 'Mike Ehrmantraut', to: 'Gus Fring', type: 'colleague', description: '雇佣关系，职业化合作', revealedAt: 15 },
    { from: 'Nacho Varga', to: 'Gus Fring', type: 'secret', description: 'Gus的棋子，被迫背叛萨拉曼卡', revealedAt: 20 },
    { from: 'Lalo Salamanca', to: 'Gus Fring', type: 'enemy', description: '致命对决，BCS最大悬念线', revealedAt: 32 },
    { from: 'Kim Wexler', to: 'Howard Hamlin', type: 'rival', description: '从下属到策划其毁灭', revealedAt: 50 },
  ],
  plotPoints: [
    { episode: 1, summary: 'Jimmy 作为公设辩护律师艰难执业，试图获得哥哥 Chuck 的认可。' },
    { episode: 9, summary: 'Jimmy 发现 Chuck 一直在暗中阻止他加入 HHM。兄弟关系开始裂痕。' },
    { episode: 10, summary: 'Chuck 录下 Jimmy 承认伪造文件的录音。' },
    { episode: 25, summary: 'Jimmy 在听证会上摧毁 Chuck 的信誉。Chuck 精神崩溃。' },
    { episode: 30, summary: 'Chuck 在家中放火自杀。Jimmy 的命运转折点。' },
    { episode: 40, summary: 'Jimmy 正式以 Saul Goodman 身份执业。与 Kim 结婚。' },
    { episode: 50, summary: 'Jimmy 和 Kim 策划针对 Howard 的阴谋开始实施。' },
    { episode: 57, summary: 'Howard 被 Lalo 当面射杀。Kim 崩溃离开 Jimmy。' },
    { episode: 58, summary: 'Lalo 与 Gus 的最终对决。Nacho 的结局。' },
    { episode: 61, summary: 'Gene 时间线：Jimmy 在 Omaha 的掩护身份暴露。' },
    { episode: 63, summary: 'Jimmy 在法庭上认罪，选择面对真相。Kim 来探监。' },
  ],
  notes: 'BB 前传 + 后传（Gene 时间线）。节奏比 BB 更慢，重人物弧线。S6 是巅峰。Kim Wexler 是整部剧最精彩的原创角色。',
};
