import type { DramaKnowledge } from '@drama-buddy/shared/knowledge';

export const gameofthrones: DramaKnowledge = {
  id: 'gameofthrones',
  title: 'Game of Thrones',
  aliases: ['权力的游戏', 'GOT', '冰与火之歌', 'A Song of Ice and Fire'],
  totalEpisodes: 73,
  genre: ['奇幻', '剧情', '冒险'],
  year: 2011,
  synopsis: '七大王国为争夺铁王座而展开的权谋斗争，同时北方长城之外的异鬼威胁日益逼近。',
  characters: [
    {
      name: 'Tyrion Lannister',
      aliases: ['小恶魔', 'The Imp', 'Halfman'],
      actor: 'Peter Dinklage',
      description: '兰尼斯特家族的侏儒次子，聪慧过人、善于言辞，家族中最被轻视却最有智慧的人。',
      personality: '机智、讽刺、善良内心、嗜酒、渴望被认可',
      firstAppearance: 1,
    },
    {
      name: 'Daenerys Targaryen',
      aliases: ['龙母', 'Khaleesi', 'Mother of Dragons', '丹妮莉丝'],
      actor: 'Emilia Clarke',
      description: '坦格利安王朝最后的后裔，从流亡公主成长为拥有三条龙的征服者。',
      personality: '坚韧、理想主义、有同情心、逐渐强硬',
      firstAppearance: 1,
    },
    {
      name: 'Jon Snow',
      aliases: ['囧雪', 'The Bastard', 'King in the North', 'Aegon Targaryen'],
      actor: 'Kit Harington',
      description: '奈德·史塔克的"私生子"，守夜人司令，身世隐藏着改变七国格局的秘密。',
      personality: '正直、沉默、有责任感、优柔寡断',
      firstAppearance: 1,
    },
    {
      name: 'Cersei Lannister',
      aliases: ['瑟曦', '狮后'],
      actor: 'Lena Headey',
      description: '兰尼斯特家族长女，先后为王后、太后、女王。为权力和子女不择手段。',
      personality: '阴狠、自负、溺爱子女、报复心强',
      firstAppearance: 1,
    },
    {
      name: 'Arya Stark',
      aliases: ['二丫', 'A Girl Has No Name', '无面者'],
      actor: 'Maisie Williams',
      description: '史塔克家族小女儿，从叛逆少女成长为致命刺客。',
      personality: '倔强、独立、复仇心切、不走寻常路',
      firstAppearance: 1,
    },
    {
      name: 'Ned Stark',
      aliases: ['奈德', 'Eddard Stark', '北境之王'],
      actor: 'Sean Bean',
      description: '北境守护、临冬城公爵。正直到近乎固执，最终为荣誉付出生命代价。',
      personality: '正直、荣誉至上、沉稳、不善权谋',
      firstAppearance: 1,
    },
    {
      name: 'Jaime Lannister',
      aliases: ['詹姆', 'Kingslayer', '弑君者'],
      actor: 'Nikolaj Coster-Waldau',
      description: '御林铁卫，因刺杀疯王而背负骂名。与姐姐瑟曦有不伦关系，后逐渐展现复杂人性。',
      personality: '傲慢→反思、勇武、矛盾、渴望救赎',
      firstAppearance: 1,
    },
    {
      name: 'Petyr Baelish',
      aliases: ['小指头', 'Littlefinger'],
      actor: 'Aidan Gillen',
      description: '御前财政大臣，七国最危险的阴谋家。从底层出身却几乎搅动了所有权力格局。',
      personality: '阴险、野心勃勃、善于操纵、自卑驱动',
      firstAppearance: 3,
    },
    {
      name: 'Night King',
      aliases: ['夜王', 'The Night King'],
      description: '异鬼之王，远古威胁的化身。率领亡灵大军南下毁灭一切生命。',
      firstAppearance: 31, // S4E04 first visual appearance
    },
  ],
  relationships: [
    { from: 'Jon Snow', to: 'Daenerys Targaryen', type: 'couple', description: '盟友→恋人→悲剧', revealedAt: 64 },
    { from: 'Jon Snow', to: 'Ned Stark', type: 'family', description: '名义上的父子', revealedAt: 1 },
    { from: 'Cersei Lannister', to: 'Jaime Lannister', type: 'secret', description: '孪生姐弟不伦关系', revealedAt: 2 },
    { from: 'Tyrion Lannister', to: 'Cersei Lannister', type: 'enemy', description: '姐弟间深仇大恨' },
    { from: 'Arya Stark', to: 'Jon Snow', type: 'family', description: '最亲密的兄妹' },
    { from: 'Daenerys Targaryen', to: 'Jon Snow', type: 'family', description: '姑侄（真实身份）', revealedAt: 67 },
    { from: 'Petyr Baelish', to: 'Ned Stark', type: 'rival', description: '表面友善实则设局' },
    { from: 'Night King', to: 'Jon Snow', type: 'enemy', description: '人类与异鬼的宿命对抗', revealedAt: 48 },
  ],
  plotPoints: [
    { episode: 1, summary: '奈德·史塔克接受国王之手职位，发现兰尼斯特家族的秘密初露端倪。' },
    { episode: 9, summary: '奈德在君临城被斩首，震惊七国。罗柏起兵反叛。' },
    { episode: 10, summary: '丹妮走入火葬堆，三条龙破壳而出。' },
    { episode: 19, summary: '黑水河之战，小恶魔以野火击溃斯坦尼斯舰队。' },
    { episode: 29, summary: '红色婚礼：罗柏、凯特琳在孪河城被屠杀。北境势力崩塌。' },
    { episode: 32, summary: '乔弗里在婚礼上被毒杀（紫色婚礼）。小恶魔被诬陷入狱。' },
    { episode: 40, summary: '小恶魔弑父越狱，流亡东方寻找丹妮莉丝。' },
    { episode: 49, summary: '琼恩在长城被叛变的守夜人刺杀。' },
    { episode: 50, summary: '红袍女复活琼恩。私生子之战夺回临冬城。' },
    { episode: 60, summary: '瑟曦用野火炸毁贝勒大圣堂，登上铁王座。' },
    { episode: 67, summary: '琼恩的真实身世揭晓：他是雷加·坦格利安与莱安娜·史塔克之子。' },
    { episode: 70, summary: '异鬼大战，二丫刺杀夜王。' },
    { episode: 72, summary: '丹妮焚毁君临城，琼恩含泪弑女王。' },
  ],
  notes: '每季10集（最终季6集）。以大量主角死亡和反转著称。适合讨论权谋、人性、命运主题。',
};
